CC=g++
CFLAGS=-g -O0 -Wall -Werror

all:chef_remove_duplicates_from_sorted_array

chef_remove_duplicates_from_sorted_array:chef_remove_duplicates_from_sorted_array.cc

clean:
	rm chef_remove_duplicates_from_sorted_array
